# Messages
ENTER = 'ENTER'
ALLOW = 'ALLOW'
RELEASE = 'RELEASE'
# Process behaviors
HEARTBEAT = "HEARTBEAT"
ACTIVE = 'ACTIVE'
PASSIVE = 'PASSIVE'
BEHAVIOR_TYPES = [ACTIVE, PASSIVE]

#timeout in s
TIMEOUT = 10
